### ISSUE TITLE
/etc/cont-init.d/add not found 

### ISSUE THREAD

**Issue by harveyche** [rocker-org/rocker-versioned#219]
I am using a dockerfile and build from image rocker/tidyverse:3.6.3 and I want to enable shiny. 
I added this line to dockerfile:
RUN export ADD=shiny && bash /etc/cont-init.d/add

When start docker build, here's the error message:
bash: /etc/cont-init.d/add: No such file or directory

**Comment by cboettig** [comment]
thanks, I'll take a look.  That should still work on the 3.6.3 image...

@noamross are we changing this mechanism in 4.0.0 image? I don't think the `add_shiny.sh` script is in the 4.0.0 rstudio recipe currently

**Comment by odonovank** [comment]
I had the same issue but switching to the latest version and using the code below in my own Dockerfile sorted it:

`FROM rocker/rstudio:latest
RUN /rocker_scripts/install_shiny_server.sh \`

**Comment by dunhampa** [comment]
I ran into this same issue.

It was resolved when I changed

`FROM rocker/geospatial`

to 

`FROM rocker/geospatial:3.6.0`

**Comment by nielsaka** [comment]
Similar here. Using `rocker/rstudio:3.6.3` and `-e ADD=shiny` shiny is installed, for version `4.0.2` it is not.

**Comment by hoegge** [comment]
Isn't it time to fix this?

**Comment by cboettig** [comment]
@hoegge as noted above, 

```
 RUN /rocker_scripts/install_shiny_server.sh
```

is the recommended way to add in shiny support on any rocker image.  Unlike the previous mechanism, this should work across the rocker versioned stack, whether or not you also use RStudio.  This is also the way to extend any image, e.g. other services (like binder) or package stacks (like the geospatial image stack) can also be added by rocker_scripts.  We believe this approach is more transparent and general then the earlier implementation.  feedback welcome.

**Comment by skranz** [comment]
Since I also stumbled over this issue, I just wanted to mention that the instructions on dockerhub here:

https://hub.docker.com/r/rocker/rstudio

still have the outdated command

```
RUN export ADD=shiny && bash /etc/cont-init.d/add
````

instead of the new command

```
RUN /rocker_scripts/install_shiny_server.sh
```

**Comment by eitsupi** [comment]
We need to refer to [the rocker-org/rocker-versioned2 repository](https://github.com/rocker-org/rocker-versioned2) on GitHub, as described as a note on the rocker/rstudio page on DockerHub.

![image](https://user-images.githubusercontent.com/50911393/130584252-97d86024-7288-46d0-945f-d654be81acf6.png)

Related Issue: https://github.com/rocker-org/rocker-versioned2/issues/191

**Comment by cboettig** [comment]
Thanks, yeah the READMEs on DockerHub have become somewhat unsynced from the READMEs on GitHub.  I've amended that Readme on DockerHub now!
